services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - C:\Users\rasmu\docker-volumes\webapi-data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_PATH=/data/auth-dev.db

# Start dev
# docker compose -f docker-compose.dev.yml up -d --build