services:
  api-prod:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - C:\Users\rasmu\docker-volumes\webapi-data\prod:/data
    environment:
      - DB_PATH=/data/auth-prod.db
      - ASPNETCORE_ENVIRONMENT=Development