services:
  api-dev:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - C:\Users\rasmu\docker-volumes\webapi-data\dev:/data
    environment:
      - DB_PATH=/data/auth-dev.db
      - ASPNETCORE_ENVIRONMENT=Development